# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: 1.5.2
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
