name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install dependencies
      run: go mod download
    
    - name: Install development tools
      run: task install-tools
    
    - name: Install required dependencies
      run: |
        go get github.com/getkin/kin-openapi/openapi3
        go get github.com/oapi-codegen/runtime
        go get github.com/oapi-codegen/runtime/types
    
    - name: Generate API client
      run: task generate
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        args: --timeout=5m
    
    - name: Run tests
      run: task test
    
    - name: Set version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Build release binaries
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: task release-build
    
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*
        generate_release_notes: true
        draft: false
        prerelease: false
        body: |
          ## Installation
          
          ### Download Binary
          Download the appropriate binary for your platform from the assets below.
          
          ### Using Installation Script
          ```bash
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/scripts/install.sh | bash
          ```
          
          ### Using in GitHub Actions
          ```yaml
          - name: Setup Coolify CLI
            uses: ${{ github.repository }}@v${{ github.ref_name }}
            with:
              version: ${{ github.ref_name }}
          ```
          
          ### Docker
          ```bash
          docker run --rm -v ~/.config/coolifyme:/home/coolify/.config/coolifyme ghcr.io/${{ github.repository }}:${{ github.ref_name }} --help
          ``` 